database_name: artspeech2
datadir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/datasets/ArtSpeech_Database_2
batch_size: 8
state_dict_fpath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/136891258768294425/f826e242117b42b8b357825ffdc644e1/artifacts/best_model.pt
vocab_filepath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/datasets/ArtSpeech_Database_2/vocabulary.json
save_to: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/136891258768294425/f826e242117b42b8b357825ffdc644e1/artifacts
num_workers: 5
articulators:
    - arytenoid-cartilage
    - epiglottis
    - lower-incisor
    - lower-lip
    - pharynx
    - soft-palate-midline
    - thyroid-cartilage
    - tongue
    - upper-lip
    - vocal-folds
test_seq_dict:
    "1775":
        - S10
        - S25
        - S28
        - S40
    "1777":
        - S37
        - S14
    "1789":
        - S37
        - S18
        - S38
    "1791":
        - S34