database_name: artspeech2
datadir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/datasets/ArtSpeech_Database_2
encoders_filepath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/812589283295778426/891ed6734523443e82aad79af83f6079/artifacts/best_encoders.pt
decoders_filepath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/812589283295778426/891ed6734523443e82aad79af83f6079/artifacts/best_decoders.pt
batch_size: 2048
save_to: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/812589283295778426/891ed6734523443e82aad79af83f6079/artifacts
num_workers: 5
model_params:
    in_features: 100
    hidden_features: 50
    indices_dict:
        tongue: 8
        lower-lip: 4
        upper-lip: 4
        soft-palate-midline: 3
        thyroid-cartilage: 2
        arytenoid-cartilage: 4
        epiglottis: 3
        lower-incisor: 3
        pharynx: 2
        vocal-folds: 2
seq_dict:
    "1775":
        - S10
        - S25
        - S28
        - S40
    "1777":
        - S37
        - S14
    "1789":
        - S37
        - S18
        - S38
    "1791":
        - S34