database_name: artspeech2
datadir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/datasets/ArtSpeech_Database_2
num_epochs: 10000
batch_size: 8
num_workers: 5
patience: 30
learning_rate: 0.00001
weight_decay: 0.000001
beta1: 0.5  # latent loss
beta2: 3.0  # reconstruction loss
beta3: 1.0  # critical loss
rescale_factor: 12.0
encoder_type: PCA
decoder_type: PCA
vocab_filepath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/datasets/ArtSpeech_Database_2/vocabulary.json
encoder_state_dict_filepath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/730963183102325621/908a44fc7a634610a3bf4a891f582f0e/artifacts/best_encoders.pt
decoder_state_dict_filepath: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/paper_files/thesis/mlruns/730963183102325621/908a44fc7a634610a3bf4a891f582f0e/artifacts/best_decoders.pt
indices_dict:
    tongue: 8
    lower-lip: 4
    upper-lip: 4
    soft-palate-midline: 3
    thyroid-cartilage: 2
    arytenoid-cartilage: 4
    epiglottis: 3
    lower-incisor: 3
    pharynx: 2
    vocal-folds: 2
TV_to_phoneme_map:
    LA:
        - p_cl
        - b_cl
        - m
    TTCD:
        - t_cl
        - d_cl
        - l
        - n
    TBCD:
        - k
        - g
rnn_type: gru
modelkwargs:
    hidden_size: 128
    embed_dim: 64
    rnn_dropout: 0.05
autoencoder_kwargs:
    in_features: 100
    hidden_features: 50
train_seq_dict:
    "1775":
        - S43
        - S11
        - S22
        - S34
        - S17
        - S30
        - S38
        - S24
        - S37
        - S13
        - S36
        - S35
        - S23
        - S20
        - S31
        - S26
        - S9
        - S8
        - S21
        - S14
        - S15
        - S27
        - S19
        - S32
        - S33
        - S29
        - S7
        - S39
        - S42
        - S16
        - S18
    "1777":
        - S39
        - S22
        - S38
        - S15
        - S18
        - S28
        - S34
        - S19
        - S17
        - S16
        - S30
        - S23
        - S26
        - S20
        - S36
        - S13
        - S25
        - S31
        - S33
        - S32
        - S27
    "1789":
        - S21
        - S41
        - S12
        - S25
        - S36
        - S40
        - S28
        - S27
        - S30
        - S20
        - S16
        - S34
        - S14
        - S22
        - S42
        - S44
        - S35
        - S17
        - S13
        - S24
        - S15
        - S31
        - S19
        - S32
        - S23
        - S39
        - S33
        - S43
    "1791":
        - S14
        - S31
        - S27
        - S33
        - S9
        - S26
        - S13
        - S35
        - S28
        - S21
        - S32
        - S20
        - S24
        - S30
        - S22
        - S37
        - S15
        - S19
        - S8
        - S29
        - S16
        - S23
        - S25
        - S11
        - S38
        - S10
        - S18
        - S12
        - S17
    "1804":
        - S16
        - S17
valid_seq_dict:
    "1775":
        - S41
        - S12
        - S6
    "1777":
        - S24
        - S21
        - S29
        - S35
    "1789":
        - S26
        - S29
    "1791":
        - S36
test_seq_dict:
    "1775":
        - S10
        - S25
        - S28
        - S40
    "1777":
        - S37
        - S14
    "1789":
        - S37
        - S18
        - S38
    "1791":
        - S34
