database_name: artspeech2
datadir: /srv/storage/talc2@talc-data2.nancy.grid5000.fr/multispeech/calcul/users/vsouzaribeiro/datasets/ArtSpeech_Database_2
n_epochs: 3000
batch_size: 2048
patience: 30
learning_rate: 0.0001
weight_decay: 0.00001
num_workers: 5
alpha: 0.1
model_params:
    in_features: 100
    hidden_features: 50
    indices_dict:
        tongue: 8
        lower-lip: 4
        upper-lip: 4
        soft-palate-midline: 3
        thyroid-cartilage: 2
        arytenoid-cartilage: 4
        epiglottis: 3
        lower-incisor: 3
        pharynx: 2
        vocal-folds: 2
train_seq_dict:
    "1775":
        - S43
        - S11
        - S22
        - S34
        - S17
        - S30
        - S38
        - S24
        - S37
        - S13
        - S36
        - S35
        - S23
        - S20
        - S31
        - S26
        - S9
        - S8
        - S21
        - S14
        - S15
        - S27
        - S19
        - S32
        - S33
        - S29
        - S7
        - S39
        - S42
        - S16
        - S18
    "1777":
        - S39
        - S22
        - S38
        - S15
        - S18
        - S28
        - S34
        - S19
        - S17
        - S16
        - S30
        - S23
        - S26
        - S20
        - S36
        - S13
        - S25
        - S31
        - S33
        - S32
        - S27
    "1789":
        - S21
        - S41
        - S12
        - S25
        - S36
        - S40
        - S28
        - S27
        - S30
        - S20
        - S16
        - S34
        - S14
        - S22
        - S42
        - S44
        - S35
        - S17
        - S13
        - S24
        - S15
        - S31
        - S19
        - S32
        - S23
        - S39
        - S33
        - S43
    "1791":
        - S14
        - S31
        - S27
        - S33
        - S9
        - S26
        - S13
        - S35
        - S28
        - S21
        - S32
        - S20
        - S24
        - S30
        - S22
        - S37
        - S15
        - S19
        - S8
        - S29
        - S16
        - S23
        - S25
        - S11
        - S38
        - S10
        - S18
        - S12
        - S17
    "1804":
        - S16
        - S17
valid_seq_dict:
    "1775":
        - S41
        - S12
        - S6
    "1777":
        - S24
        - S21
        - S29
        - S35
    "1789":
        - S26
        - S29
    "1791":
        - S36
test_seq_dict:
    "1775":
        - S10
        - S25
        - S28
        - S40
    "1777":
        - S37
        - S14
    "1789":
        - S37
        - S18
        - S38
    "1791":
        - S34
